name: example
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  convert: ^3.1.1
  json_serializable: ^6.5.4
  json_annotation: any
  model_mapper:
    path: "../model_mapper"
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
