targets:
  $default:
    builders:
      model_mapper|mapper_generator:
        generate_for:
          - test/generator_test.dart


builders:
  # name of the builder
  mapper_generator:
    # library URI containing the builder - maps to `lib/member_count_library_generator.dart`
    import: "package:model_mapper/builder.dart"
    # Name of the function in the above library to call.
    builder_factories: ["modelMapperBuilder"]
    # The mapping from the source extension to the generated file extension
    build_extensions: {".dart": [".g.dart"]}
    # Will automatically run on any package that depends on it
    auto_apply: dependents
    # Generate the output directly int
    build_to: source
  
  mapper_gen:
    import: "package:model_mapper/builder.dart"
    builder_factories: ["modelMapperBuilder"]
    build_extensions: {".dart": ["gen.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]