name: model_mapper
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.6 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  build_test: any
dependencies:
  source_gen: ^1.2.6
  build: any
  analyzer: any
  build_runner: ^2.3.3
